### ISSUE TITLE
Add "repository" property to LearningObject

### ISSUE THREAD

**Issue by gshaw1997** [Cyber4All/clark-entity#1]
Structure for property

repository: {
files: LearningObjectFile [ ],
urls: {title: string, url: string}[ ],
notes:string
}

LearningObjectFile: {
    id: string;
    name: string;
    fileType: string;
    url: string;
    date: string;
}

**Comment by ksherb1** [comment]
I can do this quickly, but first I have a few questions:
1) Will these also be stored in the database or does neutrino have its own storage solution?
2) Are there any constraints you'd like programmed directly into the entitiy? For example see how "length" is constrained to values provided by taxonomy, or the lack of an accessor ensures "author"s immutability.
3) Consistency questions:
    - Like "LearningGoals", these LearningObjectFiles and Urls can be their own entities, complete with methods to add/remove them from the object, enforce immutability, etc. Or I could just add them as interfaces and let your app manage all that. The former allows easier validation down the line and is more consistent, but you may find it more tedious to work with.
   - Is the repository encapsulation necessary? We could also have "files" and "urls" directly in LearningObject, if you'd like.

**Comment by gshaw1997** [comment]
@ksherb1 
1. They will be stored in the database. The service in Neutrino just updates the existing LearningObject with the repository property.
2. Currently there are no restraints that need to be programmed into the entity for the property.
3. Consistency
- For now just having them as interfaces will be fine. That's how they are implemented within Neutrino. I do agree that it would be best to make them their own entities eventually, but until the requirements for Neutrino are extended beyond just uploading and viewing it could be overkill.
- Originally they were just properties directly on the LearningObject, but since I'm not sure if and in what ways neutrino might expand, I encapsulated them in a single property to avoid a bunch of properties being added on to LearningObject directly that may not have any relevance within other applications.
